FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY discovery/ .
RUN go mod download
RUN CGO_ENABLED=0 go build -o /discovery ./cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /discovery /usr/local/bin/discovery
ENTRYPOINT ["discovery"]
